;; =============================================================================
;; Default values for properties
;; =============================================================================
;;
;; You are supposed to override these properties in one of the following files:
;;
;; <repository_root>/../build.properties       Common across all of your projects (passwords, not committed to Git)
;; <repository_root>/build/build.properties    Public project properties (no passwords, committed to Git)
;; <repository_root>/build/override.properties Temporary overrides for testing (passwords, not committed to Git)

; ------------------------------------------------------------------------------
; Environment
; ------------------------------------------------------------------------------
; Path to the PHP-CLI executable
system.php_cli=php
; Set to 1 to use built-in PHP XSLTproc when generating documentation. Set to 0 to use the docs.xsltproc binary (default).
docs.php_xsltproc=0
; Path to the xsltproc binary
docs.xsltproc=xsltproc

; ------------------------------------------------------------------------------
; Build stuff
; ------------------------------------------------------------------------------
; Path to the Joomla! site to symlink the extensions to
build.relink_site=
; Path to the WordPress site to symlink the plugin to
build.relink_sitewp=
; Should I allow the Joomla! package extension building to fail? Set to 1 if you are building a single component / module / plugin instead of a package containing multiple extensions.
build.allow_joomla_package_fail=0
; Version of the software being built
version=git

; ------------------------------------------------------------------------------
; Joomla! package building
; ------------------------------------------------------------------------------
; The name of the component, must be in the form something, NOT com_something!
build.component=example
; Do you have a Core / Pro version? If this is 0 only the Core release will be built
build.has_pro=1
